# Site settings
title: "Rob Day"
email: rob.day@live.com
description: > # this means to ignore newlines until "baseurl:"
  fffabs &copy 2015 - go create!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "www.##.com" # the base hostname & protocol for your site
twitter_username: robday6
github_username:  robday6

# Build settings
markdown: kramdown
permalink: ":title/"
highlighter: pygments

# Pagination
paginate: 10
paginate_path: "blog/page/:num/"

# Minification
sass:
  style: compressed
